# Exercise - Create Infra
AWSTemplateFormatVersion: 2010-09-09
Description: Create Infra With CircleCI and Ansible 
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: test-keypair1-us-east-01
      ImageId: 'ami-00874d747dde814fa' # you need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: t3.micro
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0
      Tags:
          - Key: Project
            Value: udacity