# Use the version 2.1 of CircleCI pipeline process engine.
version: 2.1

# Aliases
awsDockerImage: &awsDockerImage
  docker:
    - image: amazon/aws-cli

pythonDockerImage: &pythonDockerImage
  docker:
    - image: cimg/python:3.11

alpineDockerImage: &alpineDockerImage
  docker:
    - image: alpine:latest

# Define the jobs
jobs:
  create_infrastructure:
    # Using Docker Image as Anchor
    <<: *awsDockerImage
    # Job steps
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-infra-Stack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
  
  configure_inventory_file:
    # Using Docker Image as Anchor
    <<: *awsDockerImage
    # Job steps
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: Add EC2 IP in server-ip File
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project,Values=udacity" \
            --output text >> ~/server-ip
      - run:
          name: Display server-ip content (IP Added)
          command: |
            cat ~/server-ip
      - persist_to_workspace:
          root: ~/
          paths:
            - server-ip

  configure_infrastructure: 
    # Using Docker Image as Anchor
    <<: *pythonDockerImage
    # Job steps
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["09:fd:5c:01:13:c9:cb:12:ca:4e:dc:4c:cd:5a:aa:ac"] 
      - run:
          name: Install Ansible
          command: |
            pip install ansible
      - attach_workspace:
          at: ~/
      - run:
          name: Copy server-ip content into inventory file
          command: |
            cat ~/server-ip >> inventory && cat inventory
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml

  # Exercise: Smoke Testing
  smoke_test:
    # Using Docker Image as Anchor
    <<: *alpineDockerImage
    # Job steps
    steps:
      - attach_workspace:
          at: ~/
      - run: apk add --update curl
      - run:
          name: Display server-ip file content
          command: |
            cat ~/server-ip
      - run:
          name: Run smoke test
          command: |
            URL=`cat ~/server-ip`:3000
            echo "Test Website URL: $URL"
            if curl -s --head ${URL}
            then
              echo "It worked!" && return 0
            else
              echo "It failed" && return 1
            fi

# Sequential workflow
workflows:
  # Name the workflow
  my_workflow:
      jobs:
        - create_infrastructure
        - configure_inventory_file:
            requires:
              - create_infrastructure
        - configure_infrastructure:
            requires:
              - configure_inventory_file
        - smoke_test:
            requires:
              - configure_infrastructure
