# Use the version 2.1 of CircleCI pipeline process engine.
version: 2.1

# Aliases
awsDockerImage: &awsDockerImage
  docker:
    - image: amazon/aws-cli

# Define the jobs
jobs:
  create_infrastructure:
    # Using Docker Image as Anchor
    <<: *awsDockerImage
    # Job steps
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-infra-Stack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
  
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    # Job steps
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["72:41:d2:1c:f7:bd:15:59:33:95:22:c6:8a:05:50:48"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml

# Sequential workflow
workflows:
  # Name the workflow
  my_workflow:
      jobs:
        - create_infrastructure
        #- configure_infrastructure